### PR TITLE
Fixes #70, Try exact matches before regex matches

### LINKED ISSUE #70: Run exact match checks before regex matches
When you have many redirects, your regexs and exact matches can start to overlap. Which ones are tried first seems to be undefined. At the very least I think it makes sense that exact matches would always precede regex matches.

### PR DESCRIPTION
**Pull request by 3noch**

### CODE REVIEW

**Comment by 3noch** [comment]
This is mostly a hacky solution...but this is such an important feature that I prefer it over nothing.

**Comment by khalwat** [comment]
This is just for the stats table?

**Comment by 3noch** [comment]
Oops. I applied my old patch to your refactored code incorrectly. Check it out now.

**Comment by khalwat** [comment]
hmmm, still not seeing any other changed @3noch ...? Also could you do the PR against `develop`?

**Comment by 3noch** [comment]
I moved the patch to a different line, is all!

**Comment by 3noch** [comment]
I'd have to reopen a PR. Perhaps you'd rather just merge to `develop` when you're ready? I can start a new PR if you prefer that though.

**Comment by khalwat** [comment]
I ended up just manually adding it to the `develop` branch:

https://github.com/nystudio107/retour/tree/develop

Thx @3noch

**Comment by 3noch** [comment]
Thanks!

**Pull request closed without merging**
